// SPDX-License-Identifier: GPL-2.0-or-later
//
// The home channel: find the phone from your own laptop, with no server at all.
//
// This is the case that actually happens. Not the phone stolen in the street --
// the phone under a cushion, in a coat, behind the sofa. For that, a relay on
// the internet is a lot of machinery to reach a device eight metres away and on
// the same Wi-Fi.
//
// So: a small HTTP listener on the phone, announced over mDNS as
// `_lost-phone._tcp`, and a command on the laptop that finds it and tells it to
// scream. Nothing to host, nothing to pair with a server, nothing that stops
// working when your internet does.
//
// WHY THE ANNOUNCEMENT IS DYNAMIC AND NOT A FILE IN /etc/avahi/services
// ---------------------------------------------------------------------
// A static service file would advertise this phone as findable even with the
// feature switched off, which is both a lie and a small beacon. Registering
// through Avahi's D-Bus API means the announcement exists exactly while the
// channel does. It also costs no extra package: avahi is installed on this
// phone but avahi-tools is not, so `avahi-publish` was never an option.
//
// THE CREDENTIAL IS NOT THE SMS KEY
// ---------------------------------
// A separate token, generated by the phone. Being on the same Wi-Fi is not
// proof of anything -- guests, a neighbour who knows the password, anything
// plugged into the router -- and reusing the SMS key would mean a stranger on
// your network could read it off the phone and then use it over the carrier.

#pragma once

#include "config.h"

#include <QHash>
#include <QObject>
#include <QTcpServer>

class QTcpSocket;

class LanServer : public QObject
{
    Q_OBJECT

public:
    explicit LanServer(QObject *parent = nullptr);
    ~LanServer() override;

    // Starts, stops or restarts the listener to match the settings. Called on
    // every config change, like the relay client.
    void configure(const Settings &settings);

    bool listening() const;

    // Filled in by the daemon so /state can answer something useful without
    // this class knowing anything about ringing or locating.
    void setStatusProvider(const std::function<QByteArray()> &provider);

    // Why the last order did NOT run, or empty if it did. Asked AFTER delivering
    // it -- delivery is synchronous -- so it can answer what actually happened.
    void setResultProvider(const std::function<QString()> &provider);

Q_SIGNALS:
    void command(const QString &verb);

private:
    void onConnection();
    void handle(QTcpSocket *socket, const QByteArray &request);
    static int contentLength(const QByteArray &headers);
    void publish();
    void unpublish();

    QTcpServer m_server;

    // What has arrived so far on each open connection. A request can be split
    // across TCP segments at any point, and dropping the first half is how a
    // listener ends up hanging on the one day it is needed.
    QHash<QTcpSocket *, QByteArray> m_partial;
    Settings m_settings;
    std::function<QByteArray()> m_status;
    std::function<QString()> m_resultado;

    // The Avahi entry group's object path while the service is announced.
    QString m_entryGroup;
};
